---
title: "Explorar mapas de GRASS en R"
output: github_document
bibliography: ../biblio.bib
csl: ../apa.csl
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse=TRUE,
  fig.path = "img/",
  eval = T
)
```

<!-- Este .md fue generado a partir del .Rmd homónimo. Edítese el .Rmd -->

## Cargar paquete, activar/crear región

Más información en [Introducción a rgrass7, interfaz entre GRASS GIS 7 y R. Crear región de GRASS](intro-rgrass.md)

```{r}
library(rgrass7)
gisdbase <- 'grass-data-test' #Base de datos de GRASS GIS
wd <- getwd() #Directorio de trabajo
wd
loc <- initGRASS(gisBase = "/usr/lib/grass78/",
                 home = wd,
                 gisDbase = paste(wd, gisdbase, sep = '/'),
                 location = 'rdom',
                 mapset = "PERMANENT",
                 override = T
                 )
```

## Imprimir lista de mapas ráster y vectoriales dentro en la región/localización activa

```{r}
execGRASS(
  'g.list',
  flags = 't',
  parameters = list(
    type = c('raster', 'vector')
  )
)
```

## Cargar un mapa ráster a R y visualizarlo

```{r}
library(sp)
use_sp()
r <- readRAST('dem')
v <- readVECT('dem_extent')
plot(r)
plot(v, add=T, border='red', lwd=8)
```

## 

## Limpiar archivo de bloqueo del conjunto de mapas de GRASS

```{r}
unlink_.gislock()
```


## Referencias
